### ISSUE TITLE
README missing available fields and information on workflows

### ISSUE THREAD

**Issue by NGL321** [aws-actions/stale-issue-cleanup#13]
# 🐞 Bug 🐞 

README does not indicate available fields for workflow configuration. Additionally doesnt include general information on how to deploy a workflow (a link should be fine)

**Comment by kellertk** [comment]
@NGL321, can you check the language in #15 and see if that's clear enough?

**Comment by NGL321** [comment]
> @NGL321, can you check the language in #15 (specifically [91f6b86](https://github.com/aws-actions/stale-issue-cleanup/commit/91f6b864762ed412cd1e74f4860bcd8b654a03de)) and see if that's clear enough?

Spot on!

**Comment by kellertk** [comment]
Cool, merging.
